### ISSUE TITLE
No module named pgoapi

### ISSUE THREAD

**Issue by kalimerre** [skvvv/pikapy#1]
Hello,

When I want to launch your script it gives me "no module named pgoapi"
Can someone help me to fix it?

![pokepy](https://cloud.githubusercontent.com/assets/5664180/17496096/051645e8-5dbc-11e6-92c5-9b4b443bd0d4.PNG)

**Comment by skvvv** [comment]
Ok just a moment, forgot to put it.

**Comment by skvvv** [comment]
Can you try the following:

pip uninstall pikapy

sudo pip2 install git+https://github.com/skvvv/pikapy

pikapy

**Comment by Crisicus** [comment]
I tried what you said skvvv, but now I seem to get;
-bash: /home/crisicus/.local/bin/pikapy: No such file or directory

I was getting the same error as kalimerre

**Comment by skvvv** [comment]
Glad it's working for you :)
It's not necessary to run python scripts with sudo, unless it states in the error log as "No permission to ..."
pip though is another story, so if you have both python2 and python3 installed you will have to use pip2 everytime.

**Comment by kalimerre** [comment]
the Edit2 command was needed for me too to have the script working
Thanks @skvvv & @Crisicus
