### ISSUE TITLE
[Suggestion] Allow increments in verifiable email address along with usernames 

### ISSUE THREAD

**Issue by SpookyDaysAreHere** [skvvv/pikapy#13]
I read the other suggestion that you  may be allowing increments in the username, but is it also possible in other fields? 

Such that:

~pikapy --username=mycustomusername### --password=hunter2 --email=verifiable###@lackmail.ru -c 150

Would give you 150 accounts of 

mycustomusername1:hunter2 at verifiable1@lackmail.ru
mycustomusername2:hunter2 at verifiable2@lackmail.ru
mycustomusername3:hunter2 at verifiable3@lackmail.ru

etc.

**Comment by skvvv** [comment]
Would pretty much be same thing as usernames.
I'll get something going tomorrow
