### ISSUE TITLE
neeed help

### ISSUE THREAD

**Issue by clarkeyy** [skvvv/pikapy#14]
how do you set it up?

**Comment by paul30001** [comment]
It says right here: https://github.com/skvvv/pikapy

Basically:
-Download zip
-Unpack anywhere
-Go into the folder you just unpacked
-Right-click
-Click Open Command Window Here, or something like that
-Then paste this and hit enter: `pip install git+https://github.com/skvvv/pikapy`

If it doesn't work paste the other lines of code that you can see here
https://github.com/skvvv/pikapy

**Comment by skvvv** [comment]
well technically you would only need last 2 steps with this kind of pip install :D
