### ISSUE TITLE
What am I doing wrong?

### ISSUE THREAD

**Issue by paul30001** [skvvv/pikapy#15]
I'm trying to make it write the account info in Pokeminer format, like this:
`('ash_ketchum', 'pik4chu', 'ptc'),`

So I edited console.py, and tried restarting pikapy many times, but it still writes them into usernames.txt separated by ":"
Here's what I changed? What's wrong with it? (lines 74-76):
`with open("usernames.txt", "a") as ulist:
                ulist.write("('"+account_info[USERNAME]+"', '"+account_info[PASSWORD]+"', 'ptc'),"+"\n")
                ulist.close()`

**Comment by skvvv** [comment]
Script is installed as uneditable package.
You need to install it as editable one.


http://stackoverflow.com/questions/23075397/python-how-to-edit-an-installed-package

**Comment by paul30001** [comment]
@skvvv 
Google tells me that if it's written in pure Python, all I need is virtualenv.
But I'm not a coder, could you PLEASE list a few steps of how to edit the fork of the package.

**Comment by skvvv** [comment]
You could do the virtualenv as well, but I guess it could be easier that way:

Navigate to any folder (this is where your editable package will be installed.
Use the command:
pip uninstall pikapy (if you already have it installed as a pip package)
pip install -e git+https://github.com/skvvv/pikapy.git@master#egg=pikapeez

Now edit the files in your pikapy folder, and changes will be applied when you run pikapy command.
