### ISSUE TITLE
Error 2 while trying to install

### ISSUE THREAD

**Issue by anbux** [skvvv/pikapy#17]
https://gyazo.com/70811315461ce23283b4fb679577fb3c

https://gyazo.com/82fd8f287a4bac9e79da80301843777c

I get this error while trying to install it through read me installment and through requirements,txt. Pogom works fine for me too.

**Comment by skvvv** [comment]
You need to install git first.
then you can run the install command

**Comment by anbux** [comment]
Thank you!
