### ISSUE TITLE
pikapy is not recognized as internal or external command

### ISSUE THREAD

**Issue by anbux** [skvvv/pikapy#18]
I installed the package and try running pikapy but it comes back as this https://gyazo.com/2b7fb35633dd0317c4a7269d36062597. I have the path also to the file https://gyazo.com/2125a917aa25c7e44b4e39fa84a40d81 so that shouldn't be a problem, I have pogom too so idk what im doing wrong.

**Comment by paul30001** [comment]
And you're sure you've properly installed pip and pikapy? Also, which Python version are you using. 

Here are my EV, maybe try adding ones related to Python... 
![screenshot 41](https://cloud.githubusercontent.com/assets/20823132/17581408/71b6ed98-5f5a-11e6-8947-e0bec22aaa85.png)

**Comment by anbux** [comment]
Yes it's installed fine https://gyazo.com/d9d5d0dbf414e7c94e1df046f72ac158 , i do have it installed and i tried this and it still doesnt work https://gyazo.com/d2f93a979eb333bbbc299e970f3da0ee

**Comment by paul30001** [comment]
Start from scratch, try in virtualenv.
