### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by brianhrowe** [skvvv/pikapy#20]
I was able to install everything without a problem using:

> pip install git+https://github.com/skvvv/pikapy

However, when pikapy with any of the suggested methods of creating accounts I get the following output

> ~$ pikapy -c 10
> Traceback (most recent call last):
>   File "/usr/local/bin/pikapy", line 5, in <module>
>     from pkg_resources import load_entry_point
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
>     working_set = WorkingSet._build_master()
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
>     ws.require(__requires__)
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
>     raise DistributionNotFound(req)
> pkg_resources.DistributionNotFound: ndg-httpsclient

**Comment by skvvv** [comment]
try this:

pip install ndg_httpsclient

**Comment by brianhrowe** [comment]
@skvvv yeah it was some dependency issues. Thanks!. Got that and a few more cleared up and it's working. To you knowledge do you have to login to the accounts on the web for them to work with scanners?

**Comment by skvvv** [comment]
@brianhrowe they are scanner ready after they are created.

only for 2 days though
