### ISSUE TITLE
Death By Captcha support?

### ISSUE THREAD

**Issue by brettgus** [skvvv/pikapy#24]
Any thoughts on fixing these issues by adding death by captcha support?

**Comment by TheDDoSFriend** [comment]
https://github.com/skvvv/pikapy/blob/master/README.md

**Comment by Mickey32111** [comment]
@TheDDoSFriend Do you have any idea when your site will be open to the public?

**Comment by TheDDoSFriend** [comment]
@Mickey32111 We do not know when it will be public, but we are working on the site as hard as we can.

**Comment by Mickey32111** [comment]
@TheDDoSFriend That's good enough for me :)
