### ISSUE TITLE
I need 100-300 accounts, can anyone please give me some? 

### ISSUE THREAD

**Issue by paul30001** [skvvv/pikapy#25]
I only created a few accounts thinking there'll always be more time, but no, should've created a few thousand when I had the chance.
Anyway, if any of you created a lot, could you please spare some? What's a few hundred if you have thousands?  :)

**Comment by skvvv** [comment]
Pikapy accounts never got mail verified. We were almost ready to push 0.3 up, and captcha happened.
So none created by it will work anymore.
