### ISSUE TITLE
Account Creation Still Working?

### ISSUE THREAD

**Issue by VisualStudio-zz** [skvvv/pikapy#3]
This isn't an issue but I was wondering if this still works because it seems that there's a lot of javascript behind the account creation process and I can't seem to get your script to work. If it doesn't do you want to collaborate and get one up and working? I have a lot of the javascript rewritten in python so it shouldn't be too hard.

**Comment by skvvv** [comment]
![screen](https://cloud.githubusercontent.com/assets/12024563/17505841/54abc572-5e04-11e6-85bc-87a2ee00dbd6.png)

It is working, albeit the first account takes some time to pop up. Could be Niantic?
Except from pgoapi, which I have nothing to do with, this is written 100% in python.
However I'm all up for collabs, and making this script better, as it needs lots of work and rewriting.

**Comment by VisualStudio-zz** [comment]
Do you use slack by any chance? I use slack for text messages and code plus teamspeak for voice. If that's not ok then I can make a discord channel if you want?

**Comment by skvvv** [comment]
You could make a discord for now, will get slack soon.

**Comment by VisualStudio-zz** [comment]
https://discord.gg/AQTqw

**Comment by bukubuke** [comment]
is this related to https://github.com/jepayne1138/PTCAccount/blob/master/README.rst by any chance?

**Comment by skvvv** [comment]
Yeah the accountcreator.py is almost the same, planning on reworking it as there are more and more invalid responses, and it's taking more time to do the job right.
