### ISSUE TITLE
chromedriver executable needs to be in PATH

### ISSUE THREAD

**Issue by trippyhat** [skvvv/pikapy#30]
Using Ubuntu 16.04. I followed the instructions in the README, but when I ran `pikapy` I see this error:

```
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
```

**Comment by skvvv** [comment]
You could either do what's linked or install chromium:

sudo apt-get install chromium-browser

**Comment by trippyhat** [comment]
@skvvv I did install chromium driver. Here is the steps I did:
```
sudo apt-get install chromium-browser
sudo pip install git+https://github.com/skvvv/pikapy
```
After that I ran `pikapy`

And the error pops up.

**Comment by 4mp3d** [comment]
Same issue I think. 

Installed Chromium as instructions say. Then had to get selenium and the pgoapi. Then I run it and I get: 
`Attempting to create user traskwizbruss:skapshovplask. Opening browser...
Traceback (most recent call last):
  File "/usr/local/bin/pikapy", line 9, in <module>
    load_entry_point('Pikapy==0.3', 'console_scripts', 'pikapy')()
  File "/home/asieting/.local/lib/python2.7/site-packages/pikapy/console.py", line 60, in entry
    account_info = pikapy.random_account(args.username, args.password, args.email, args.birthday, args.plusmail)
  File "/home/asieting/.local/lib/python2.7/site-packages/pikapy/accountcreator.py", line 208, in random_account
    account_created = create_account(try_username, password, try_email, try_birthday)
  File "/home/asieting/.local/lib/python2.7/site-packages/pikapy/accountcreator.py", line 108, in create_account
    driver = webdriver.Chrome()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 62, in __init__
    self.service.start()
  File "/usr/local/lib/python2.7/dist-packages/selenium/webdriver/common/service.py", line 71, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

Exception AttributeError: "'Service' object has no attribute 'process'" in <bound method Service.__del__ of <selenium.webdriver.chrome.service.Service object at 0x7f84dcfdd810>> ignored`

**Comment by 4mp3d** [comment]
http://stackoverflow.com/a/24364290

Downloaded the latest from here http://chromedriver.storage.googleapis.com/index.html and did as the instructions say. Unzip it. Move it to /usr/bin/ and then chmod a+x. But now I'm getting: 

![image](https://cloud.githubusercontent.com/assets/21044682/17757563/b8952e9a-64b5-11e6-9204-6e76022687d5.png)

**Comment by skvvv** [comment]
@4mp3d thanks for this link, for some people it just works out of the box. Will add this to readme.
