### ISSUE TITLE
Chromium no 32btït¨¨

### ISSUE THREAD

**Issue by Kundvagnsverktyg** [skvvv/pikapy#31]
I got this error because its trying to download an 32bit version but it does not exist, only 64bit

curl: (22) The requested URL returned error: 404 Not Found
Error: Failed to download resource "chromedriver"
Download failed: https://chromedriver.storage.googleapis.com/2.23/chromedriver_mac32.zip

**Comment by skvvv** [comment]
you are trying that with homebrew I guess?

**Comment by AndreasEnemyr** [comment]
Ye

**Comment by Mickey32111** [comment]
To update the brew formula, use this:
`brew edit chromedriver
`
And then change the line url from ...mac32.zip to
`"https://chromedriver.storage.googleapis.com/2.23/chromedriver_mac64.zip"`

and sh256 goes like that:
`sha256 "47a8caec6ce251f2dbaa9005e4dc783cb1fa6c09ecd76afafa41eab540a32e86"`

now `brew uninstall chromedriver` (if you have installed the 32bit one)
and `brew install chromedriver`

**Comment by Kundvagnsverktyg** [comment]
Thanks! it works, just remember to:

To finish editing, do `esc` then `:wq` W=Write and Q=Quit
