### ISSUE TITLE
No module named 'selenium'?

### ISSUE THREAD

**Issue by paul30001** [skvvv/pikapy#32]
Followed all instructions and got this. 

I had old pikapy installed, but I updated it so I should be good, right? 
Plus it says during the installation process "uninstalled" and then "installed pikapy 0.3."

*Does this work on Python 3.5? It has before.

![screenshot 59](https://cloud.githubusercontent.com/assets/20823132/17751749/5da7f9aa-647d-11e6-9e0b-be4e1e651a9a.png)

**Comment by CosmoRing** [comment]
Had the same problem. i just did `pip install selenium` on the console and it start working.

**Comment by jahe** [comment]
I hat the same problem and solved it just like @CosmoRing.

**Comment by paul30001** [comment]
@CosmoRing 
@jahe 
I did that and it helped, but now when running "pikapy" I get no module named Strings!
And doing `pip install strings gives the following error. :(
Here's 2 screenshots. Guys heeeeelp!


![screenshot 61](https://cloud.githubusercontent.com/assets/20823132/17763374/245c20ea-64cd-11e6-94ce-cdeba4f76a6b.png)
![screenshot 60](https://cloud.githubusercontent.com/assets/20823132/17763400/3e96b9fc-64cd-11e6-8a19-5cb190c886ab.png)

**Comment by skvvv** [comment]
strings.py is a script inside pikapy folder not a pip module
I'll change the name now I guess it's a bad idea anyways.
Try doing pip uninstall pikapy
Then the standard pip install git+...
