### ISSUE TITLE
[Request] Details from txt or CSV file

### ISSUE THREAD

**Issue by DJ-666** [skvvv/pikapy#34]
Would be great to have the ability to pull a list of usernames, passwords and emails from a txt or CSV file to be created.

**Comment by PassiveModding** [comment]
just as an output with username:password:email or something similar would be very handy

**Comment by skvvv** [comment]
https://github.com/skvvv/pikapy/commit/619b914c1ab374ffbe2baae3c6c5fed797346d9d
