### ISSUE TITLE
[Request] Base Username

### ISSUE THREAD

**Issue by PassiveModding** [skvvv/pikapy#40]
Like what you have with the gmail trick just have a base username for all accounts made in a cerain batch
eg. ~pikapy -u YourAccount -p password -m YourEmail+@gmail.com -c 3
Then the accounts made would be:
YourAccount1:password
YourAccount2:password
YourAccount3:password
etc.
or the Username with a random number sequence after eg.
YourAccount1290:password
YourAccount9224:password
etc.

**Comment by PassiveModding** [comment]
also a little batch file to make things simpler for windows users
![2a69c8f23efbc096daa41ffe7e231fd2](https://cloud.githubusercontent.com/assets/20432486/17779147/fb61943a-65a9-11e6-9e08-dc5afd212814.png)

"@echo off
echo Running...
pikapy -p password -m email+@gmail.com -c 2
echo Complete!
pause>nul
exit"

**Comment by Mumpitz** [comment]
Yes, i would like to have that too.

Was looking for a solution that can create more account that follow my current pattern.
I already created 15 Accounts by hand and verified them by hand as well.

The pattern is:
Username: NameX
E-Mail: Name+X@gmail.com
Password: pass

All accounts share the same Password and the same BaseName for Name and E-Mail Address.
Now i would like to continue in an automated way, from 16 to X. If that could be implemented, i would be very happy. :)
