### ISSUE TITLE
Will not run on mac os

### ISSUE THREAD

**Issue by smoo7h** [skvvv/pikapy#45]
I get this error everytime I try to run this on my mac os. It works fine for me on linux

Traceback (most recent call last):
  File "/usr/local/bin/pikapy", line 9, in <module>
    load_entry_point('Pikapy==0.3', 'console_scripts', 'pikapy')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2570, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2230, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2236, in resolve
    module = **import**(self.module_name, fromlist=['**name**'], level=0)
  File "/usr/local/lib/python2.7/site-packages/pikapy/console.py", line 7, in <module>
    from pgoapi import PGoApi
  File "/Users/mmccann/Downloads/PokemonGo-Map-develop/src/pgoapi/pgoapi/**init**.py", line 50, in <module>
    from pgoapi.pgoapi import PGoApi
  File "/Users/mmccann/Downloads/PokemonGo-Map-develop/src/pgoapi/pgoapi/pgoapi.py", line 34, in <module>
    from pgoapi.rpc_api import RpcApi
  File "/Users/mmccann/Downloads/PokemonGo-Map-develop/src/pgoapi/pgoapi/rpc_api.py", line 44, in <module>
    from POGOProtos.Networking.Envelopes_pb2 import RequestEnvelope
  File "/Users/mmccann/Downloads/PokemonGo-Map-develop/src/pgoapi/pgoapi/protos/POGOProtos/Networking/Envelopes_pb2.py", line 16, in <module>
    from POGOProtos.Networking import Requests_pb2 as POGOProtos_dot_Networking_dot_Requests__pb2
  File "/Users/mmccann/Downloads/PokemonGo-Map-develop/src/pgoapi/pgoapi/protos/POGOProtos/Networking/Requests_pb2.py", line 23, in <module>
    ENCOUNTER\x10\x91\x01\x12!\n\x1c\x43OLLECT_DAILY_DEFENDER_BONUS\x10\x92\x01\x12\x14\n\x0fUPGRADE_POKEMON\x10\x93\x01\x12\x19\n\x14SET_FAVORITE_POKEMON\x10\x94\x01\x12\x15\n\x10NICKNAME_POKEMON\x10\x95\x01\x12\x10\n\x0b\x45QUIP_BADGE\x10\x96\x01\x12\x19\n\x14SET_CONTACT_SETTINGS\x10\x97\x01\x12\x15\n\x10GET_ASSET_DIGEST\x10\xac\x02\x12\x16\n\x11GET_DOWNLOAD_URLS\x10\xad\x02\x12\x1c\n\x17GET_SUGGESTED_CODENAMES\x10\x91\x03\x12\x1d\n\x18\x43HECK_CODENAME_AVAILABLE\x10\x92\x03\x12\x13\n\x0e\x43LAIM_CODENAME\x10\x93\x03\x12\x0f\n\nSET_AVATAR\x10\x94\x03\x12\x14\n\x0fSET_PLAYER_TEAM\x10\x95\x03\x12\x1b\n\x16MARK_TUTORIAL_COMPLETE\x10\x96\x03\x12\x16\n\x11LOAD_SPAWN_POINTS\x10\xf4\x03\x12\t\n\x04\x45\x43HO\x10\x9a\x05\x12\x1b\n\x16\x44\x45\x42UG_UPDATE_INVENTORY\x10\xbc\x05\x12\x18\n\x13\x44\x45\x42UG_DELETE_PLAYER\x10\xbd\x05\x12\x17\n\x12SFIDA_REGISTRATION\x10\xa0\x06\x12\x15\n\x10SFIDA_ACTION_LOG\x10\xa1\x06\x12\x18\n\x13SFIDA_CERTIFICATION\x10\xa2\x06\x12\x11\n\x0cSFIDA_UPDATE\x10\xa3\x06\x12\x11\n\x0cSFIDA_ACTION\x10\xa4\x06\x12\x11\n\x0cSFIDA_DOWSER\x10\xa5\x06\x12\x12\n\rSFIDA_CAPTURE\x10\xa6\x06\x62\x06proto3')
TypeError: **init**() got an unexpected keyword argument 'syntax'

**Comment by Mickey32111** [comment]
Please run `pip freeze` in your terminal and paste the output.

**Comment by voignar** [comment]
The same happens to me.
The pip freezee:

C:\Python27\pikapi>pip freeze
alabaster==0.7.9
argh==0.26.2
Babel==2.3.4
backports-abc==0.4
certifi==2016.8.8
cffi==1.7.0
click==6.6
colorama==0.3.7
CommonMark==0.5.4
ConfigArgParse==0.10.0
cryptography==1.4
docutils==0.12
enum34==1.1.6
Flask==0.11.1
Flask-CacheBust==1.0.0
Flask-Compress==1.3.0
Flask-Cors==2.1.2
future==0.15.2
geopy==1.11.0
gpsoauth==0.3.0
idna==2.1
imagesize==0.7.1
ipaddress==1.0.16
itsdangerous==0.24
Jinja2==2.8
LatLon==1.0.1
livereload==2.4.1
MarkupSafe==0.23
ndg-httpsclient==0.4.2
pathtools==0.1.2
peewee==2.8.1
pgoapi==1.1.6
Pikapy==0.3
port-for==0.3.1
protobuf==3.0.0
protobuf-to-dict==0.1.0
pyasn1==0.1.9
pycparser==2.14
pycryptodomex==3.4.2
Pygments==2.1.3
PyMySQL==0.7.5
pyOpenSSL==16.0.0
pyproj==1.9.5.1
PySocks==1.5.6
pytz==2016.6.1
PyYAML==3.11
recommonmark==0.4.0
requests==2.10.0
s2sphere==0.2.4
selenium==2.53.6
singledispatch==3.4.0.3
six==1.10.0
snowballstemmer==1.2.1
Sphinx==1.4.5
sphinx-autobuild==0.6.0
sphinx-rtd-theme==0.1.9
tornado==4.4.1
watchdog==0.8.3
Werkzeug==0.11.10
xxhash==0.6.1

**Comment by ctr26** [comment]
I had this problem when my system was using python3 rather than python.  Run python -v and paste here

**Comment by voignar** [comment]
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
# C:\Python27\lib\site.pyc matches C:\Python27\lib\site.py
import site # precompiled from C:\Python27\lib\site.pyc
# C:\Python27\lib\os.pyc matches C:\Python27\lib\os.py
import os # precompiled from C:\Python27\lib\os.pyc
import errno # builtin
import nt # builtin
# C:\Python27\lib\ntpath.pyc matches C:\Python27\lib\ntpath.py
import ntpath # precompiled from C:\Python27\lib\ntpath.pyc
# C:\Python27\lib\stat.pyc matches C:\Python27\lib\stat.py
import stat # precompiled from C:\Python27\lib\stat.pyc
# C:\Python27\lib\genericpath.pyc matches C:\Python27\lib\genericpath.py
import genericpath # precompiled from C:\Python27\lib\genericpath.pyc
# C:\Python27\lib\warnings.pyc matches C:\Python27\lib\warnings.py
import warnings # precompiled from C:\Python27\lib\warnings.pyc
# C:\Python27\lib\linecache.pyc matches C:\Python27\lib\linecache.py
import linecache # precompiled from C:\Python27\lib\linecache.pyc
# C:\Python27\lib\types.pyc matches C:\Python27\lib\types.py
import types # precompiled from C:\Python27\lib\types.pyc
# C:\Python27\lib\UserDict.pyc matches C:\Python27\lib\UserDict.py
import UserDict # precompiled from C:\Python27\lib\UserDict.pyc
# C:\Python27\lib\_abcoll.pyc matches C:\Python27\lib\_abcoll.py
import _abcoll # precompiled from C:\Python27\lib\_abcoll.pyc
# C:\Python27\lib\abc.pyc matches C:\Python27\lib\abc.py
import abc # precompiled from C:\Python27\lib\abc.pyc
# C:\Python27\lib\_weakrefset.pyc matches C:\Python27\lib\_weakrefset.py
import _weakrefset # precompiled from C:\Python27\lib\_weakrefset.pyc
import _weakref # builtin
# C:\Python27\lib\copy_reg.pyc matches C:\Python27\lib\copy_reg.py
import copy_reg # precompiled from C:\Python27\lib\copy_reg.pyc
# C:\Python27\lib\traceback.pyc matches C:\Python27\lib\traceback.py
import traceback # precompiled from C:\Python27\lib\traceback.pyc
# C:\Python27\lib\sysconfig.pyc matches C:\Python27\lib\sysconfig.py
import sysconfig # precompiled from C:\Python27\lib\sysconfig.pyc
# C:\Python27\lib\re.pyc matches C:\Python27\lib\re.py
import re # precompiled from C:\Python27\lib\re.pyc
# C:\Python27\lib\sre_compile.pyc matches C:\Python27\lib\sre_compile.py
import sre_compile # precompiled from C:\Python27\lib\sre_compile.pyc
import _sre # builtin
# C:\Python27\lib\sre_parse.pyc matches C:\Python27\lib\sre_parse.py
import sre_parse # precompiled from C:\Python27\lib\sre_parse.pyc
# C:\Python27\lib\sre_constants.pyc matches C:\Python27\lib\sre_constants.py
import sre_constants # precompiled from C:\Python27\lib\sre_constants.pyc
import _locale # builtin
# C:\Python27\lib\locale.pyc matches C:\Python27\lib\locale.py
import locale # precompiled from C:\Python27\lib\locale.pyc
import encodings # directory C:\Python27\lib\encodings
# C:\Python27\lib\encodings\__init__.pyc matches C:\Python27\lib\encodings\__init__.py
import encodings # precompiled from C:\Python27\lib\encodings\__init__.pyc
# C:\Python27\lib\codecs.pyc matches C:\Python27\lib\codecs.py
import codecs # precompiled from C:\Python27\lib\codecs.pyc
import _codecs # builtin
# C:\Python27\lib\encodings\aliases.pyc matches C:\Python27\lib\encodings\aliases.py
import encodings.aliases # precompiled from C:\Python27\lib\encodings\aliases.pyc
import operator # builtin
# C:\Python27\lib\functools.pyc matches C:\Python27\lib\functools.py
import functools # precompiled from C:\Python27\lib\functools.pyc
import _functools # builtin
# C:\Python27\lib\encodings\cp1252.pyc matches C:\Python27\lib\encodings\cp1252.py
import encodings.cp1252 # precompiled from C:\Python27\lib\encodings\cp1252.pyc
Python 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.

**Comment by skvvv** [comment]
well, now we are sure he is running python 2.7 :D

**Comment by jdkullmann** [comment]
Any word on how to fix this?  I'm definitely running 2.7, and getting the same error running OS X

**Comment by jdkullmann** [comment]
I just did 'brew rm protobuf' and that fixed this issue for me

**Comment by ibruno** [comment]
Error: No such keg: /usr/local/Cellar/protobuf

didn't work for me
