### ISSUE TITLE
Hi dude pip can not install from github due to "sudo" comment can not run on windows

### ISSUE THREAD

**Issue by shadowxers** [skvvv/pikapy#5]
i take error when i try to install pip via sudo comment or your other way on the page

**Comment by skvvv** [comment]
Could you post what the error is?

**Comment by skvvv** [comment]
Ok now that you have updated the title:

"sudo" is linux only command
on windows, just do:

 pip install git+https://github.com/skvvv/pikapy

before that however, you need to get pip:

http://stackoverflow.com/questions/4750806/how-do-i-install-pip-on-windows
