### ISSUE TITLE
Ptc Account Creator

### ISSUE THREAD

**Issue by cliffsmits007** [skvvv/pikapy#52]
i have installed evreything corectly  but i dont know the command how to create accounts for PTC when i do. 

~pikapy
Created new account:
  Username:  traynagmoh
  Password:  rossstrubhep
  Email   :  fantsniskflast@gastsnub.com

i recieve into cmd 

C:\WINDOWS\System32>  Email   :  linkslampnob@gastsnub.com
'Email' is not recognized as an internal or external command,
operable program or batch file.

**Comment by skvvv** [comment]
command is just:
pikapy
