### ISSUE TITLE
Stopped working today

### ISSUE THREAD

**Issue by matpag** [skvvv/pikapy#53]
Today the automatic creation of the accounts stopped working.
Now the accounts that have not been activated from email wont work anymore.

2016-08-22 19:52:51,543 [ search_worker_1][      auth_ptc][   ERROR] Could not retrieve token: Account is not yet active, please redirect.

Anybody else the same problem?

**Comment by skvvv** [comment]
It is working fine, accounts expire after 2 days ( no email verification).
I linked another repo which is a fork of this, that handles email verification
