### ISSUE TITLE
Runtime.evaluate missing 'wasThrown

### ISSUE THREAD

**Issue by Mickey32111** [skvvv/pikapy#58]
Hey, I've used pikapy many times without issues. However today when I went to run it. It's deciding to throw me an error instead.

![screen shot 2016-08-24 at 00 48 23](https://cloud.githubusercontent.com/assets/5605121/17913781/87098df6-6994-11e6-8549-4cbebdcac4ba.png)

I can confirm I'm running the latest version of Pikapy with all dependencies installed. I have no idea what caused this error because I've changed nothing since last time it was working fine.

**Comment by wenom64** [comment]
+1
the same problem

**Comment by Mickey32111** [comment]
It's because you either don't have chrome installed or you have a beta of dev version. Uninstall and install the standard release version. @wenom64

**Comment by wenom64** [comment]
For me, this is not the solution. I need this DEV version of Chrome for my work.

**Comment by Mickey32111** [comment]
@wenom64 you can run the canary version along side the standard version. I'm not sure about the dev branch though.
