### ISSUE TITLE
new acount lvl 22 wrong credentials 

### ISSUE THREAD

**Issue by Theo1996** [skvvv/pikapy#64]
i made a new account it run for 4 days perfectly and now it says wronf credentials,what do?

**Comment by kara71** [comment]
Maybe you got banned ? Check the accont's emails

**Comment by Theo1996** [comment]
what the trash emails? they dissapear i made new accounts with my gmail will see if they get the wrong credentilas error too.

**Comment by Theo1996** [comment]
uppon further inspection the accounts say that they are verified even though they are not so after 2 days they dissapear.

**Comment by skvvv** [comment]
Not email verified, read the readme.
