### ISSUE TITLE
Account wasn't activated yet.

### ISSUE THREAD

**Issue by robiningelbrecht** [skvvv/pikapy#66]
Seems like every 24h I need to create new accounts, because the old ones return "Account was not valiated yet". I use these accounts with my pokemonGo application.

Anyone knows about this problem?

**Comment by hoidaan** [comment]
Me too.. I think niantic kills accounts.. When I used real email addresses for the pokemon go map server I received emails from niantic that they shutdown my accounts because I was using them for illegal causes of something like that..

**Comment by hoidaan** [comment]
Maybe this happens because we cannot activate the accounts because we use random email accounts (i do)

**Comment by robiningelbrecht** [comment]
After checking the readme carefully, I am now using the more sofisticated script, which has email verification build in.

**Comment by hoidaan** [comment]
@robiningelbrecht thanks bro! :) got it working perfectly again!
