### ISSUE TITLE
ImportError: No module named pgoapi

### ISSUE THREAD

**Issue by unixb0y** [skvvv/pikapy#69]
I get this error when I want to execute pikapy on mac after successful installation.
Why?
`ImportError: No module named pgoapi
`
Thank you in advance.

**Comment by aviram83** [comment]
You can run the command:
pip install -e git://github.com/tejado/pgoapi.git#egg=pgoapi

work for me

**Comment by pedropetz** [comment]
aviram83, doing that give me "NameError: name 'xrange' is not defined"
