### ISSUE TITLE
[Suggestion] Allow username patterns in account creation

### ISSUE THREAD

**Issue by Lim-Dul** [skvvv/pikapy#8]
I have a suggestion that would greatly help with managing accounts:

How about a way to create accounts with usernames following a certain pattern. E.g.

pikapy -u Username## -c 2

Would create two accounts with incremental numbers in the username - Username01 and Username02

**Comment by Maxxxel** [comment]
need this too

**Comment by skvvv** [comment]
I'll do it today.

**Comment by Maxxxel** [comment]
where???
