### ISSUE TITLE
Connection broken: IncompleteRead

### ISSUE THREAD

**Issue by charredchar** [skvvv/pikapy#9]
I have been attempting to run this for a few hours, creating accounts to data mine. After just a short period, about 30 minutes, I will get the following error and need to restart by hand. I am also unsure if the last account created actually verified the ToS when this happens.

> Traceback (most recent call last):
>   File "C:\Python27\Scripts\pikapy-script.py", line 9, in <module>
>     load_entry_point('Pikapy==0.2', 'console_scripts', 'pikapy')()
>   File "c:\python27\lib\site-packages\pikapy\console.py", line 60, in entry
>     args.username, args.password, args.email, args.email_tag
>   File "c:\python27\lib\site-packages\pikapy\accountcreator.py", line 404, in random_account
>     try_username, password, try_email
>   File "c:\python27\lib\site-packages\pikapy\accountcreator.py", line 244, in create_account
>     resp_code=200
>   File "c:\python27\lib\site-packages\pikapy\accountcreator.py", line 99, in request
>     resp = self.send(prepped)
>   File "c:\python27\lib\site-packages\requests\sessions.py", line 606, in send
>     history = [resp for resp in gen] if allow_redirects else []
>   File "c:\python27\lib\site-packages\requests\sessions.py", line 179, in resolve_redirects
>     **adapter_kwargs
>   File "c:\python27\lib\site-packages\requests\sessions.py", line 617, in send
>     r.content
>   File "c:\python27\lib\site-packages\requests\models.py", line 741, in content
>     self._content = bytes().join(self.iter_content(CONTENT_CHUNK_SIZE)) or bytes()
>   File "c:\python27\lib\site-packages\requests\models.py", line 667, in generate
>     raise ChunkedEncodingError(e)
> requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

**Comment by kton111** [comment]
Same error here. Please add try catch on this part to keep the program in loop.
Thanks so much !

**Comment by skvvv** [comment]
Until this get fixed, if you are doing bigger ammount of accounts e.g. -c 100, dont do it in one instance
instead go:

pikapy -p password -c 10 & pikapy -p password -c 10 ... (copy paste 10 times)

not only is it faster, but it should prevent broken connections.
so only one or two instances might shut down giving you 80-90 accounts instead of 0

**Comment by skvvv** [comment]
I guess it's fixed, currently troubleshooting, will post update if it works well.
Problem is im not getting any of these exceptions to be sure it's actually fixed :(
